version: "3.8"

services:
  db2:
    image: ibmcom/db2
    container_name: db2-container
    privileged: true
    ports:
      - "50000:50000"
    environment:
      LICENSE: "accept"
      DB2INST1_PASSWORD: "password"
      DBNAME: "db2_test"
    volumes:
      - db2data:/database
      - ./dbscripts:/database/scripts 
    restart: unless-stopped

volumes:
  db2data:
