-- Creating the users table with JSON support
CREATE TABLE users (
    id NUMBER PRIMARY KEY, 
    data CLOB CONSTRAINT ensure_json CHECK (data IS JSON)
);

-- Inserting JSON data into the users table
INSERT INTO users (id, data) 
VALUES (
    1, 
    '{
        "name": "John Doe", 
        "email": "john.doe@example.com", 
        "address": {"city": "New York", "zip": "10001"}, 
        "orders": [
            {"order_id": 101, "amount": 250.5, "status": "shipped"}, 
            {"order_id": 102, "amount": 120.0, "status": "pending"}
        ]
    }'
);

-- Creating the products table with JSON support
CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255),
    category VARCHAR2(100),
    details CLOB CONSTRAINT ensure_json_details CHECK (details IS JSON),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
