version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-demo
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=password
    volumes:
      - oracle-data:/opt/oracle/oradata
volumes:
  oracle-data: